



logging.level:
  root: INFO
  com.example.lab01.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true
    enable:
      root: false
      jvm: true

opentracing:
  jaeger:
    serviceName: lab01
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://localhost:14268/api/traces
#    udp-sender:
#      host: localhost
#      port: 6831


server:
  port: 7070

spring:
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
    user: root
    password: password
    locations: classpath:db/migration/lab01
    #schemas: dbo
    #flyway-schemas: flyway-schemas
    group: false

lab01:
  event:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  db01:
    url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
    username: lab01user
    password: lab01userpwd
    driverClassName: com.mysql.cj.jdbc.Driver

  features:
    crypto.key: 123456789012345678901234567890
    panicEnabled: false
    ctaCteApi:
      url: http://localhost:7071/accounts
    ctaAhoApi:
      url: http://localhost:7071/accounts

crypto.key: "keyvalue"