# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docke hub'
        repository: 'mzegarra/lab06-devops'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/src/main/docker/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: '$(tag)'